[build]
  command = "./deploy.sh"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# Force HTTPS for all connections
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    
# Direct access to static version
[[redirects]]
  from = "/static"
  to = "/static.html"
  status = 200

# Success page for Netlify deployments
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
    
# For single page applications (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200