[build]
  command = "./deploy.sh"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

# Force HTTPS for all connections
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    
# For single page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Fallback to static version if React app doesn't load
[[redirects]]
  from = "/static"
  to = "/static/index.html"
  status = 200